title: Zabbix Event Sensors
description: Zabbix Event Sensors imports Zabbix problem events into Home Assistant as sensors.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
